version: 2

multi-ecosystem-groups:
  weekly-dependency-updates:
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Etc/UTC

updates:
  - package-ecosystem: github-actions
    directory: /
    patterns: ["*"]
    multi-ecosystem-group: weekly-dependency-updates
    groups:
      security-updates:
        applies-to: security-updates
        patterns: ["*"]
    open-pull-requests-limit: 5
  - package-ecosystem: pip
    directory: /
    patterns: ["*"]
    multi-ecosystem-group: weekly-dependency-updates
    groups:
      security-updates:
        applies-to: security-updates
        patterns: ["*"]
    open-pull-requests-limit: 5
